export const RECEIVE_USERS = "RECEIVE_USERS";
export const SET_AUTHED_USER = "SET_AUTHED_USER";
export const LOGOUT_AUTHED_USER = "LOGOUT_AUTHED_USER";
export const RECEIVE_POLLS = "RECEIVE_POLLS";
export const ADD_POLL = "ADD_POLL";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
